services:
  todo-fe:
    build: ./frontend
    ports:
      - "89:80"

  todo-be:
    build: ./backend
    links:
      - "todo-db"
    ports:
      - "3000:3000"

  todo-db:
    image: mongo:latest
    volumes:
      - H:\001_MyData\07_Learning\02_NEST_LEAP4\src\projects\todo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
